export const toolsAndTechStacksData = [
  {
    src: "/images/html5.svg",
    title: "HTML5",
    value: 95,
    txtValue: "95%",
    strokeColor: "stroke-orange-600",
  },
  {
    src: "/images/css3.svg",
    title: "CSS3",
    value: 95,
    txtValue: "95%",
    strokeColor: "stroke-sky-600",
  },
  {
    src: "/images/php.svg",
    title: "PHP",
    value: 80,
    txtValue: "80%",
    strokeColor: "stroke-indigo-300",
  },
  {
    src: "/images/react.svg",
    title: "ReactJs",
    value: 90,
    txtValue: "90%",
    strokeColor: "stroke-sky-300",
  },
  {
    src: "/images/laravel.svg",
    title: "Laravel",
    value: 75,
    txtValue: "75%",
    strokeColor: "stroke-red-400",
  },
  {
    src: "/images/nodejs.svg",
    title: "NodeJs",
    value: 75,
    txtValue: "70%",
    strokeColor: "stroke-lime-500",
  },
  {
    src: "/images/mysql.svg",
    title: "MySQL",
    value: 90,
    txtValue: "80%",
    strokeColor: "stroke-orange-400",
  },
  {
    src: "/images/typescript.svg",
    title: "TypeScript",
    value: 90,
    txtValue: "80%",
    strokeColor: "stroke-sky-600",
  },
  {
    src: "/images/postman.svg",
    title: "Postman",
    value: 85,
    txtValue: "85%",
    strokeColor: "stroke-orange-600",
  },
  {
    src: "/images/docker.svg",
    title: "Docker",
    value: 85,
    txtValue: "80%",
    strokeColor: "stroke-sky-400",
  },
  {
    src: "/images/material-ui.svg",
    title: "Material UI (MUI)",
    value: 90,
    txtValue: "90%",
    strokeColor: "stroke-sky-700",
  },
  {
    src: "/images/vue.svg",
    title: "VueJs",
    value: 85,
    txtValue: "85%",
    strokeColor: "stroke-emerald-500",
  },
  {
    src: "/images/graphql.svg",
    title: "GraphQL",
    value: 80,
    txtValue: "80%",
    strokeColor: "stroke-pink-600",
  },
  {
    src: "/images/typeorm.svg",
    title: "TypeORM",
    value: 75,
    txtValue: "75%",
    strokeColor: "stroke-red-600",
  },
  {
    src: "/images/prisma.svg",
    title: "Prisma",
    value: 80,
    txtValue: "80%",
    strokeColor: "stroke-slate-700",
  },
];

export const projectArr = [
  {
    heading: "Reymart Militante Portfolio",
    body: "A personal portfolio designed and built to showcase my work, experience, and approach to creating thoughtful web applications.",
    image: "/images/portfolio-preview.png",
    status: "Live",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS"],
    codeUrl: "https://github.com/martmilitante/portfolio",
    liveUrl: "https://reymartmilitante.dev/",
  },
  {
    heading: "RankPilot AI",
    body: "An AI-first SEO operating system that turns website data into clear, prioritized action through crawling, issue detection, recommendations, and professional reports.",
    image: null,
    status: "In development",
    technologies: ["Next.js", "TypeScript", "PostgreSQL", "AI"],
    codeUrl: "https://github.com/martmilitante/rankpilot-ai",
    liveUrl: null,
  },
  {
    heading: "Client Work",
    body: "Selected client projects are kept private under confidentiality agreements and are not available for public display.",
    image: null,
    status: "Private",
    technologies: ["Frontend", "Backend", "Product engineering"],
    codeUrl: null,
    liveUrl: null,
  },
];
