import Image from "next/image";
import React from "react";

const ToolsAndTechStacks = () => {
  return (
    <div
      id="tools-and-techstacks"
      className="flex flex-wrap justify-center gap-6 px-56"
    >
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
        alt="html5"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
        alt="javascript"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/laravel/laravel-plain-wordmark.svg"
        alt="laravel"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
        alt="aws"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/babeljs/babeljs-icon.svg"
        alt="babel"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg"
        alt="bootstrap"
        width="80"
        height="80"
      />
      <Image
        src="https://www.chartjs.org/media/logo-title.svg"
        alt="chartjs"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/angularjs/angularjs-original-wordmark.svg"
        alt="angularjs"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
        alt="css3"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg"
        alt="docker"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
        alt="express"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/figma/figma-icon.svg"
        alt="figma"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg"
        alt="firebase"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg"
        alt="gcp"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg"
        alt="git"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg"
        alt="linux"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
        alt="mysql"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
        alt="nodejs"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg"
        alt="php"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg"
        alt="postgresql"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/getpostman/getpostman-icon.svg"
        alt="postman"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
        alt="react"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg"
        alt="sass"
        width="80"
        height="80"
      />
      <Image
        src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
        alt="sqlite"
        width="80"
        height="80"
      />
      <Image
        src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg"
        alt="typescript"
        width="80"
        height="80"
      />
    </div>
  );
};

export default ToolsAndTechStacks;
